development:
  adapter: mysql2
  encoding: utf8
  database: freemarket_sample_68b_development
  pool: 5
  username: root
  password: <%= ENV['68b'] %>
  socket: /tmp/mysql.sock
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: freemarket_sample_68b_test
  pool: 5
  username: root
  password: <%= ENV['68b'] %>
  socket:  /tmp/mysql.sock
